version: '3.3'
services:
  pgadmin4:
    container_name: pgadmin-container
    image: 'dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
    user: root
  redis:
    container_name: redis-container
    image: 'redis:latest'
    ports:
      - '6379:6379'
  postgres:
    container_name: postgres-container
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: seo_dashboard
    ports:
      - '5432:5432'
    volumes:
      - './postgres-data:/var/lib/postgres/data'
